version: '3.8'
services:
    # CONFIG TO USE LARAVEL SAIL - But I prefered use NGINX 
    # app:
    #     container_name: api_app
    #     build:
    #         context: ./docker/php
    #         dockerfile: Dockerfile
    #         args:
    #             WWWGROUP: '${WWWGROUP}'
    #     image: sail-8.2/app
    # extra_hosts:
    #     - 'host.docker.internal:host-gateway'
    # ports:
    #     - '${APP_PORT:-80}:80'
    #     - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    # environment:
    #     WWWUSER: '${WWWUSER}'
    #     LARAVEL_SAIL: 1
    #     XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    #     XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    # volumes:
    #     - '.:/var/www/html'
    # networks:
    #     - sail
    # depends_on:
    #     - redis
    app:
        container_name: api_app
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - web_api
        ports:
            - 8000:8000
        depends_on:
            - redis

    redis:
        container_name: api_redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - web_api
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    web_api:
        driver: bridge
volumes:
    redis:
        driver: local