name: IdezApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

env:
  PROJECT_ID: ${GCLOUD_PROJECT_ID}
  REGION: us-central1
  REPO_NAME: cloud-run-source-deploy/idez/idez-app

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install (Composer)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --ignore-platform-req=ext-swoole

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Tests
        env:
          SERVICE_COUNTY: brasil_api_service
        run: vendor/bin/phpunit --testsuite=Internal
        
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          version: '358.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          export IMAGE_TAG=${{ secrets.GCLOUD_SHA }}
          export IMAGE_PATH=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}@sha256:${IMAGE_TAG}
          docker build -t $IMAGE_PATH .
          docker push $IMAGE_PATH

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-service \
            --image=${IMAGE_PATH} \
            --platform=managed \
            --region=${REGION} \
            --allow-unauthenticated