name: IdezApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install (Composer)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --ignore-platform-req=ext-swoole

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Tests
        env:
          SERVICE_COUNTY: brasil_api_service
        run: vendor/bin/phpunit --testsuite=Internal

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          version: '358.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}

      - name: Configure Docker
        run: |
          echo ${{ secrets.GCLOUD_AUTH_KEY }} | base64 -d > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud auth configure-docker

      - name: Build and push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/idez-app .
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/idez-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy idez-app \
            --image=gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/idez-app \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
      - name: Trigger Google Cloud Build
        env:
          GCLOUD_TRIGGER_URL: ${{ secrets.GCLOUD_TRIGGER_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" -H "X-Goog-Resource-Name: $GCLOUD_TRIGGER_URL" -H "Authorization: Bearer $(gcloud auth print-access-token)" https://cloudbuild.googleapis.com/v1/projects/idez-app/locations/global/triggers/69bf9495-9589-4066-923c-e5fed19607d2

